name: Build
on: [push, pull_request]

jobs:
  ubuntu-gcc-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccache clang lld python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install cmake ninja wheel pybind11
      - name: Build
        run: |
          export TRITON_PLUGIN_DIRS=$(pwd)
          cd triton/python
          python3 -m pip install -e .
      - name: Verify installation
        run: |
          cd triton/python
          python3 -c 'import triton; triton.runtime.driver.set_active(triton.backends.backends["acc"].driver())'
