name: Lint
on: [push, pull_request]

jobs:
  py-check-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup environment
        run: |
          python3 -m pip install ruff==0.1.3
      - name: Run ruff
        run: |
          python3 -m ruff .
  py-check-yapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup environment
        run: |
          python3 -m pip install git+https://github.com/google/yapf@be72557
      - name: Run yapf
        run: |
          python3 -m yapf -rdp .
      - name: Check for difference
        run: |
          git diff --exit-code
